# Generated by Django 5.0.6 on 2024-05-18 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('has_physical_store', models.BooleanField(default=False)),
                ('physical_shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('physical_shop_address', models.TextField(blank=True, null=True)),
                ('physical_shop_city', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_shop_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('online_shop_type', models.CharField(blank=True, choices=[('electronics', 'Electronics Shop'), ('household', 'Household Shop'), ('clothing', 'Clothing Shop')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
