# Generated by Django 5.0.2 on 2024-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='has_physical_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='online_shop_type',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics Shop'), ('household', 'Household Shop'), ('clothing', 'Clothing Shop')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='physical_shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='physical_shop_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='physical_shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='physical_shop_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
