# Generated by Django 5.0.2 on 2024-04-19 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchant_has_physical_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
