# Generated by Django 5.0.2 on 2024-05-08 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchant_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='id',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
