# Generated by Django 5.0.6 on 2024-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_merchant_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='bank_account_number',
            field=models.CharField(default=14522665, max_length=20),
            preserve_default=False,
        ),
    ]
