# Generated by Django 5.0.6 on 2024-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('merchant', 'Merchant'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
