# Generated by Django 5.0.2 on 2024-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_first_name_remove_account_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
