# Generated by Django 5.0.2 on 2024-05-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_customer_account_is_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_merchant',
        ),
    ]
