# Generated by Django 5.0.6 on 2024-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('merchant', 'Merchant'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
