# Generated by Django 5.0.6 on 2024-07-19 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Last name')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP')),
                ('city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=1024, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
