# Generated by Django 5.0.6 on 2024-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
