# Generated by Django 5.0.2 on 2024-05-14 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/preview/'),
        ),
        migrations.AddField(
            model_name='shoprating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoprating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shoprating',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoprating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
