# Generated by Django 5.0.2 on 2024-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='css',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
