# Generated by Django 5.0.2 on 2024-04-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_delete_store'),
        ('shop', '0003_shop_css_shop_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='css',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='html',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='template',
        ),
        migrations.CreateModel(
            name='CustomizedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.template')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
                ('customized_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='shop.customizedtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='customized_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customizedtemplate'),
        ),
    ]
