# Generated by Django 5.0.2 on 2024-04-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shop_css_remove_shop_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='customized_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customizedtemplate'),
        ),
    ]
