# Generated by Django 5.0.2 on 2024-05-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_remove_merchant_id_alter_merchant_unique_id'),
        ('shop', '0005_alter_shop_customized_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedtemplate',
            name='modifiedby',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
            preserve_default=False,
        ),
    ]
