# Generated by Django 5.0.2 on 2024-05-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_remove_merchant_id_alter_merchant_unique_id'),
        ('shop', '0006_customizedtemplate_modifiedby_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedtemplate',
            name='modifiedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_templates', to='merchant.merchant'),
        ),
    ]
