# Generated by Django 5.0.2 on 2024-05-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_customizedtemplate_modifiedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
