# Generated by Django 5.0.2 on 2024-04-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_page_remove_template_css_remove_template_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='css',
        ),
        migrations.RemoveField(
            model_name='page',
            name='html',
        ),
        migrations.RemoveField(
            model_name='page',
            name='js',
        ),
        migrations.RemoveField(
            model_name='template',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='builder.template'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.page')),
            ],
        ),
    ]
