# Generated by Django 5.0.2 on 2024-04-04 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_remove_page_css_remove_page_html_remove_page_js_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css',
            field=models.TextField(default='hello{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(default='hello{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='js',
            field=models.TextField(default='alert()'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='builder.template'),
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
