# Generated by Django 5.0.2 on 2024-04-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_template_category_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
