# Generated by Django 5.0.2 on 2024-05-12 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('paymentStatus', models.CharField(max_length=20)),
                ('payment', models.CharField(max_length=50)),
                ('shippingMethod', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('placedBy', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
